### ISSUE TITLE
Supported lamps and API version

### ISSUE THREAD

**Issue by fzmemon** [stoman/MilightAPI#1]
Hi,
I have the CW/WW milight build. Does this API support those? Additionally is the v6 milight API supported?

**Comment by stoman** [comment]
The software is only tested with RGB+W light bulbs that are a little older already. In terms of Easybulb, I tested them for the Easybulb models and not yet for the Easybuld Plus models which use the v6 API. It seems like there will be some changes necessary here, but I don't own the light bulbs you mentioned and thus can't test them yet.

Modifications and additions to the project are always welcome! I would appreciate if you added support for the newer light bulbs. In the mean time you can try and have a look at https://github.com/happyleavesaoc/python-limitlessled which seems to support your build.
