### ISSUE TITLE
More explaination

### ISSUE THREAD

**Issue by fdelavra** [stoman/MilightAPI#2]
Hello. 

I have tried to use your api as you have explained in your README but failed. 

I have a iBox2 of mi-light as a wifi box connected to my network. 
I have created a WifiBox with the ip of my iBox2. 
When I try to do box.on() or any other command nothing happen. 
I don’t have any error but no light turns ooh. 

Can you explain me exactly how to install and use your api?

thanks

**Comment by stoman** [comment]
Thanks for trying my API! This was not tested with the iBox2, but only with the older version. The tested boxes look like this: https://cdn.webshopapp.com/shops/38765/files/27386857/mi-light-milight-wifi-empfaenger-controller-box.jpg

I'm not sure whether the interface is the same for both versions of the box, but could easily imagine that they changed the format. I would recommend to try connecting with the app using the same box first. If you can't get your lights to switch on/off after that it's likely to be an incompatible device. Calling `box.on()` is everything that should be required.

**Comment by fdelavra** [comment]
Thanks for answering me.
I have tried every configuration possible with the iBox2 without success.
A simple python library make the job so I oriented my choice with this solution

Le 4 mars 2021 à 00:02, Stefan Toman <notifications@github.com> a écrit :

﻿

Thanks for trying my API! This was not tested with the iBox2, but only with the older version. The tested boxes look like this: https://cdn.webshopapp.com/shops/38765/files/27386857/mi-light-milight-wifi-empfaenger-controller-box.jpg

I'm not sure whether the interface is the same for both versions of the box, but could easily imagine that they changed the format. I would recommend to try connecting with the app using the same box first. If you can't get your lights to switch on/off after that it's likely to be an incompatible device. Calling box.on() is everything that should be required.

**Comment by stoman** [comment]
It's great to hear you found another solution for your hardware. Have fun building with that!
